Repository mpv-player/mpv, pull requests merged in 2023-08, with the labels that each got.

#12097 test/meson: add missing avutil dependency to chmap test
  test/meson.build
Labels: meta:build

#12096 ao_audiotrack features & fixes
  DOCS/interface-changes.rst
  audio/out/ao_audiotrack.c
Labels: os:android

#7824 ao/jack: set device_buffer to JACK buffer size
  audio/out/ao_jack.c
Labels: priority:stalled

#7813 ao/pulse: implement period_size
  audio/out/ao_pulse.c
Labels: priority:stalled
